### PR TITLE
Use KDE Platform 5.9

### PR DESCRIPTION
**Pull request by dsboger**

### CODE REVIEW

**Comment by dsboger** [comment]
bot, build

**Comment by TingPing** [comment]
Curious if you had any specific problems with 5.10 and if they are reported?

**Comment by dsboger** [comment]
@TingPing none at all. It is just that there are GNOME platform extensions available for Qt 5.9, and FMIT works equally well with both.

**Comment by TingPing** [comment]
The platform extensions are packaged for both.

**Comment by dsboger** [comment]
Really? I could install `org.kde.PlatformTheme.QGnomePlatform//5.9` and `org.kde.KStyle.Adwaita/x86_64/5.9` from `kdeapps`, but could not find anything `//5.10` nor anything from `flathub` at all. Am I missing something?

**Comment by TingPing** [comment]
No my mistake, turns out you are right. We are probably blocked waiting on a solution for https://github.com/flathub/flathub/pull/283

**Pull request merged**
