### PR TITLE
remove fftw

### PR DESCRIPTION
**Pull request by eszlari**
It's included in the runtime since v5.12.

### CODE REVIEW

**Comment by gillesdegottex** [comment]
Why trying to remove FFTW3 ? This is necessary for the FourierTranform module.

**Comment by eszlari** [comment]
fftw is included in the freedesktop runtime, which the KDE runtime is based on:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/elements/desktop/fftw.bst

**Comment by gillesdegottex** [comment]
So FFTW is installed anyway as soon as flathub is used ?
(sorry but I vaguely know that flathub is a package manager and freedesktop is a standardisation of desktops ...)

**Comment by eszlari** [comment]
> So FFTW is installed anyway as soon as flathub is used ?

It is available, when you use version 5.12 of the KDE runtime in your flatpak build manifest:
```
"runtime" : "org.kde.Platform",
"sdk" : "org.kde.Sdk",
"runtime-version" : "5.12",
```

> (sorry but I vaguely know that flathub is a package manager and freedesktop is a standardisation of desktops ...)

http://docs.flatpak.org/en/latest/basic-concepts.html#runtimes

**Comment by gillesdegottex** [comment]
But FMIT is independant on KDE.
Is FFTW still available without KDE ?

**Comment by dsboger** [comment]
Hi, thanks for looking into this. FMIT is having some trouble to compile for arm architectures with the 5.12 runtime. It seems FMIT contains some non-portable Qt/GL code. I've started working on porting some of that code to QPainter, but haven't got enough time to put that proposal into decent shape.

As an immediate solution, I'd switch back to the 5.9 runtime, meaning that fftw would still need to be bundled (I think).

**Comment by dsboger** [comment]
@gillesdegottex in flatpak world, every app had the choose a runtime to depend on. It is mostly a set of libraries. FMIT depends on kde runtime because it comes with Qt. That doesn't mean it depends on the kde plasma desktop.

**Comment by eszlari** [comment]
> As an immediate solution, I'd switch back to the 5.9 runtime, meaning that fftw would still need to be bundled (I think).

You could also disable the arm builds:
https://github.com/flathub/flathub/wiki/App-Maintenance#limiting-the-set-of-architectures-to-build-on

**Comment by dsboger** [comment]
@eszlari can I be sure no one is using FMIT on arm? Do you know if there is some statistics to help me with that?

**Comment by eszlari** [comment]
https://flathub.org/stats/

**Comment by dsboger** [comment]
bot, build

**Comment by dsboger** [comment]
The build is failing due to added strictness in the AppData validation. I've PR'ed some fixes upstream and once the build passes I'll merge this. Thanks again!

**Comment by hfiguiere** [comment]
I have an appdata patch part of #12

**Comment by gillesdegottex** [comment]
I got lost between these PR, I've merged #12 whose tests were passing.
I guess I can close this one, right ?

**Comment by hfiguiere** [comment]
yes it can be closed.

**Pull request closed without merging**
